language: php
php: "5.6"
services: postgresql
before_install:
 - psql -c 'create database bukatoko;' -U postgres
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install 
script: phpunit UnitTestingTest.php
matrix:
 allow_failures: 
  php: "5.6"
 fast_finish: true